[package]
name = "hexagon-engine"
version = "0.1.0"
authors = ["Jakub Sapalski <coosheck@gmail.com>"]
edition = "2018"

[dependencies]
websocket = "0.22.0"
futures = "0.1.25"
tokio = "0.1.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.6.5"
names = "0.11.0"